"""purge_fluff

Revision ID: 17f162425a53
Revises: 502fe9bb52b6
Create Date: 2026-07-17 23:06:03.099375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f162425a53'
down_revision: Union[str, None] = '502fe9bb52b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('none', 'starter', 'growth', 'pro', 'elite', name='usertier', native_enum=False, length=20),
               nullable=False,
               existing_server_default=sa.text("'none'"))
        batch_op.alter_column('monthly_message_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_message_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tier',
               existing_type=sa.Enum('none', 'starter', 'growth', 'pro', 'elite', name='usertier', native_enum=False, length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'none'"))

    # ### end Alembic commands ###
