"""initial_migration

Revision ID: 502fe9bb52b6
Revises: 
Create Date: 2026-07-17 22:36:56.374600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502fe9bb52b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'client', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='userstatus', native_enum=False, length=20), nullable=False),
    sa.Column('tier', sa.Enum('none', 'starter', 'growth', 'pro', 'elite', name='usertier', native_enum=False, length=20), nullable=False),
    sa.Column('industry_niche', sa.String(length=50), nullable=True),
    sa.Column('monthly_message_count', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_link_token', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('rules_mode', 'ai_mode', 'closed', name='chatsessionstate', native_enum=False, length=20), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('current_rule_index', sa.Integer(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('tracking_data', sa.JSON(), nullable=True),
    sa.Column('pending_messages', sa.JSON(), nullable=False),
    sa.Column('is_processing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_client_id'), 'chat_sessions', ['client_id'], unique=False)
    op.create_table('chat_widget_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('widget_name', sa.String(length=255), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('theme_color', sa.String(length=7), nullable=False),
    sa.Column('rejection_message', sa.Text(), nullable=False),
    sa.Column('downsell_url', sa.Text(), nullable=True),
    sa.Column('allowed_domains', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('ai_api_key', sa.Text(), nullable=True),
    sa.Column('rules_config', sa.JSON(), nullable=True),
    sa.Column('intent_threshold', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('security_protocol', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('ai_apply_chat_widget', sa.Boolean(), nullable=False),
    sa.Column('ai_apply_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('ai_goals', sa.JSON(), nullable=True),
    sa.Column('debounce_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_widget_configs_client_id'), 'chat_widget_configs', ['client_id'], unique=True)
    op.create_table('client_payment_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_keys', sa.JSON(), nullable=True),
    sa.Column('custom_payment_link', sa.Text(), nullable=True),
    sa.Column('generic_webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_payment_configs_user_id'), 'client_payment_configs', ['user_id'], unique=True)
    op.create_table('google_ads_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('developer_token', sa.Text(), nullable=False),
    sa.Column('oauth_client_id', sa.Text(), nullable=False),
    sa.Column('oauth_client_secret', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('login_customer_id', sa.Text(), nullable=False),
    sa.Column('target_customer_id', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_ads_credentials_user_id'), 'google_ads_credentials', ['user_id'], unique=False)
    op.create_table('magic_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('min_score_to_qualify', sa.Integer(), nullable=False),
    sa.Column('rejection_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_forms_client_id'), 'magic_forms', ['client_id'], unique=False)
    op.create_table('orchestrator_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestrator_logs_user_id'), 'orchestrator_logs', ['user_id'], unique=False)
    op.create_table('saved_strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('headlines', sa.JSON(), nullable=False),
    sa.Column('descriptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_strategies_user_id'), 'saved_strategies', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('chat_transcript', sa.JSON(), nullable=True),
    sa.Column('gclid', sa.String(length=200), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('consultation_paid', sa.Boolean(), nullable=False),
    sa.Column('consultation_amount', sa.Float(), nullable=True),
    sa.Column('full_case_paid', sa.Boolean(), nullable=False),
    sa.Column('full_case_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.create_index(op.f('ix_leads_session_id'), 'leads', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_session_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_client_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_saved_strategies_user_id'), table_name='saved_strategies')
    op.drop_table('saved_strategies')
    op.drop_index(op.f('ix_orchestrator_logs_user_id'), table_name='orchestrator_logs')
    op.drop_table('orchestrator_logs')
    op.drop_index(op.f('ix_magic_forms_client_id'), table_name='magic_forms')
    op.drop_table('magic_forms')
    op.drop_index(op.f('ix_google_ads_credentials_user_id'), table_name='google_ads_credentials')
    op.drop_table('google_ads_credentials')
    op.drop_index(op.f('ix_client_payment_configs_user_id'), table_name='client_payment_configs')
    op.drop_table('client_payment_configs')
    op.drop_index(op.f('ix_chat_widget_configs_client_id'), table_name='chat_widget_configs')
    op.drop_table('chat_widget_configs')
    op.drop_index(op.f('ix_chat_sessions_client_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
